version: '3'

networks:
  prisma-network:
    driver: bridge

services:
  mongodb:
    image: 'mongo'
    container_name: 'my-mongo-container'
    environment:
      - MONGO_INITDB_DATABASE=prisma
    volumes:
      - ./mongo-volume:/data/db
    networks:
      - prisma-network
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host

  prisma-service:
    build: ../
    ports:
      - 8080:8080
    networks:
      - prisma-network

